name: moya_app
description: MOYA 생리 관리 앱

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_blue_plus: ^1.32.0   # 1.3x 대 버전 아무거나 최신
  permission_handler: ^11.3.1  # (Android 권한 런타임 요청용)
  flutter_bluetooth_serial: ^0.4.0
  shared_preferences: ^2.2.0
  camera: ^0.10.5+5
  http: ^1.2.1 #chatGPT
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  provider: ^6.0.5
  flutter_svg: ^2.2.0
  lottie: ^3.3.1
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  flutter_reactive_ble: ^5.3.1 #ble 통신

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/scan.json
    - assets/lottie/sa.json
    - assets/lottie/searching.json

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900