// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAguQYVLT7L9c7D--Ll4BfW3omMx2XgswQ',
    appId: '1:996921654382:android:8aeb753615325d56f07a7f',
    messagingSenderId: '996921654382',
    projectId: 'moya-ff7e0',
    storageBucket: 'moya-ff7e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeJl2H0lzScWq3zTNgpV-VT3YAGBMUyeY',
    appId: '1:996921654382:ios:0990d12110c93a00f07a7f',
    messagingSenderId: '996921654382',
    projectId: 'moya-ff7e0',
    storageBucket: 'moya-ff7e0.firebasestorage.app',
    iosBundleId: 'com.example.moya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeJl2H0lzScWq3zTNgpV-VT3YAGBMUyeY',
    appId: '1:996921654382:ios:0990d12110c93a00f07a7f',
    messagingSenderId: '996921654382',
    projectId: 'moya-ff7e0',
    storageBucket: 'moya-ff7e0.firebasestorage.app',
    iosBundleId: 'com.example.moya',
  );
}
